steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${SHORT_SHA}", "."]
substitutions:
  _IMAGE: "gce-metadata-simulator"
  _LOCATION: "us-west1"
  _REPOSITORY: "simulator"
images:
  - "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${SHORT_SHA}"
