apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: simulator-config
    files:
      - default_settings.py

patchesStrategicMerge:
  - deployment.yaml
