apiVersion: apps/v1
kind: Deployment
metadata:
  name: gce-metadata-simulator
spec:
  selector:
    matchLabels:
      app: gce-metadata-simulator
  template:
    metadata:
      labels:
        app: gce-metadata-simulator
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
        - name: gce-metadata-simulator
          image: us-west1-docker.pkg.dev/rueth-anthos-hybrid/simulator/gce-metadata-simulator:ef9088d
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
