apiVersion: v1
kind: Service
metadata:
  name: gce-metadata-simulator
spec:
  type: ClusterIP
  selector:
    app: gce-metadata-simulator
  ports:
    - name: http
      port: 80
      targetPort: 5000
